services:
  launchly:
    build:
      context: .
      dockerfile: Containerfile
    image: localhost/launchly:dev
    container_name: launchly
    network_mode: host
    security_opt:
      - label=disable
    volumes:
      - /run/podman/podman.sock:/run/podman/podman.sock
      - /tmp/launchly:/tmp/launchly:rw
    restart: unless-stopped
